
package com.javaedu;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "todolistService", targetNamespace = "http://www.javaedu.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TodolistService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.RegisterResponse")
    @Action(input = "http://www.javaedu.com/todolistService/registerRequest", output = "http://www.javaedu.com/todolistService/registerResponse")
    public String register(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.LoginResponse")
    @Action(input = "http://www.javaedu.com/todolistService/loginRequest", output = "http://www.javaedu.com/todolistService/loginResponse")
    public String login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryItem", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.QueryItem")
    @ResponseWrapper(localName = "queryItemResponse", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.QueryItemResponse")
    @Action(input = "http://www.javaedu.com/todolistService/queryItemRequest", output = "http://www.javaedu.com/todolistService/queryItemResponse")
    public String queryItem(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addItem", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.AddItem")
    @ResponseWrapper(localName = "addItemResponse", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.AddItemResponse")
    @Action(input = "http://www.javaedu.com/todolistService/addItemRequest", output = "http://www.javaedu.com/todolistService/addItemResponse")
    public String addItem(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteItem", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.DeleteItem")
    @ResponseWrapper(localName = "deleteItemResponse", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.DeleteItemResponse")
    @Action(input = "http://www.javaedu.com/todolistService/deleteItemRequest", output = "http://www.javaedu.com/todolistService/deleteItemResponse")
    public String deleteItem(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItemList", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.GetItemList")
    @ResponseWrapper(localName = "getItemListResponse", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.GetItemListResponse")
    @Action(input = "http://www.javaedu.com/todolistService/getItemListRequest", output = "http://www.javaedu.com/todolistService/getItemListResponse")
    public String getItemList();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "clearItem", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.ClearItem")
    @ResponseWrapper(localName = "clearItemResponse", targetNamespace = "http://www.javaedu.com", className = "com.javaedu.ClearItemResponse")
    @Action(input = "http://www.javaedu.com/todolistService/clearItemRequest", output = "http://www.javaedu.com/todolistService/clearItemResponse")
    public String clearItem();

}
